!Main_Workflow.yml [V9]
Version 9 of the main workflow file for this project.

diff --git a/.github/workflows/!Main_Workflow.yml b/.github/workflows/!Main_Workflow.yml
--- a/.github/workflows/!Main_Workflow.yml
+++ b/.github/workflows/!Main_Workflow.yml
@@ -4,6 +4,7 @@
 # This workflow was made due to possible truncation issues with GitHub once the workflows directory reaches 1000 items. This workflow will not be functional for a while.
 
 # Support workflows
+# Astro (GitHub Pages)
 # Ada (GNAT)
 # Android CI
 # Ant (Java)
@@ -281,6 +282,96 @@
 # Mallard
 
 # A section
+
+# Astro (GitHub pages)
+
+# Sample workflow for building and deploying an Astro site to GitHub Pages
+#
+# To get started with Astro see: https://docs.astro.build/en/getting-started/
+#
+name: Deploy Astro site to Pages
+
+on:
+  # Runs on pushes targeting the default branch
+  push:
+    branches: ["master"]
+
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+# Allow one concurrent deployment
+concurrency:
+  group: "pages"
+  cancel-in-progress: true
+
+env:
+  BUILD_PATH: "." # default value when not using subfolders
+  # BUILD_PATH: subfolder
+
+jobs:
+  build:
+    name: Build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: "16"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json
+      - name: Setup Pages
+        id: pages
+        uses: actions/configure-pages@v2
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+        working-directory: ${{ env.BUILD_PATH }}
+      - name: Build with Astro
+        run: |
+          ${{ steps.detect-package-manager.outputs.runner }} astro build \
+            --site "${{ steps.pages.outputs.origin }}" \
+            --base "${{ steps.pages.outputs.base_path }}"
+        working-directory: ${{ env.BUILD_PATH }}
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v1
+        with:
+          path: ${{ env.BUILD_PATH }}/dist
+
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    needs: build
+    runs-on: ubuntu-latest
+    name: Deploy
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
 
 # Ada
 
@@ -5651,9 +5742,15 @@ jobs:
 # Updated the supported workflow list
 # Updated the change log
 # Updated the file info section
+# V9 (2022, Thursday, November 24th at 9:58 pm PST)
+# Added support for Astro (GitHub Pages)
+# Updated the supported workflow list
+# Updated the change log
+# Updated the file info section
 
 # File info
 # File type: YAML source file (*.yml *.yaml)
-# File version: 8 (2022, Wednesday, September 21st at 9:00 pm PST)
-# Line count (including blank lines and compiler line): 5,660
+# File version: 9 (2022, Thursday, November 24th at 9:58 pm PST)
+# Line count (including blank lines and compiler line): 5,757
+
 # End of script
